#!/bin/bash
## bash script clean.sh
## usage: clean.sh dir
## helps to rm unwanted files from a directory
if (( $# != 1 )) ## number of args is not 1
then echo usage: $0 directory
	exit 1
fi
dir="$1"
if ! [[ -d "$dir" && -w "$dir" ]] ## not a dir or not writable
then echo $dir not a writable directory
	echo usage: $0 directory; exit 1
fi

cd "$dir";

for file in * 
do 
	if ! [[ -f "$file" && -r "$file" ]] 
		then continue 
	fi 
	echo " " ## a blank line 
	/bin/ls -l "$file" 
	while : 
	do 
		echo -n "*** Delete $file or not?? " 
		echo -n "[y, n, e, m, t, ! or q]:" 
		read c
		case $c in
			y) if [[ ! -w "$file" ]] 
    				then echo $file write-protected 
    				else /bin/rm "$file" 
					if [[ -e "$file" ]]
					then echo cannot delete $file 
					else echo "+++++ $file deleted" 
				fi 
   			fi
	break ;;


	n) echo "----- $file not deleted"
	break ;; 


	e) ${EDITOR:-/bin/vi} "$file"; continue ;;
	m) /bin/more "$file"; continue ;; 
	t) /bin/tail "$file"; continue ;; 
	!) echo -n "command: " 
	read cmd 
	eval $cmd ;;
	q) break 2;; ## break 2 levels
	*) ## help for user echo clean commands: followed by RETURN 
	echo "y yes delete file" 
	echo "n don't delete file, skip to next file" 
	echo "e edit/view file with ${EDITOR:-/bin/vi}" 
	echo "m display file with more" 
	echo "t display tail of file" 
	echo "! Shell escape" 
	echo "q quit, exit from clean" 
	;; 
	esac 
	done 
done
